### ISSUE TITLE
Documentation - interactive mode - wrong command? 

### ISSUE THREAD

**Issue by jzabl** [musevlt/zap#11]
In `index.rst` on line 222, where the interactive mode is described, it says: 

`zobj.writefits(outcubefits='DATACUBE_FINAL_ZAP.fits')`

Shouldn't this be: 

`zobj.mergefits(outcubefits='DATACUBE_FINAL_ZAP.fits')`

Thanks,
Johannes

**Comment by saimn** [comment]
Yes, good catch, thanks Johannes!
