### ISSUE TITLE
NaN left in zapped data cube

### ISSUE THREAD

**Issue by RolandBacon** [musevlt/zap#13]
dir08 = '/muse/MXDF/private/data/reduced/0.8/zap/gradeAB'
dname = dir08+'/DATACUBE_ZAP.fits'
cube = Cube(dname)
sp = cube07[1000:1040,200,200]
sp.data
masked_array(data=[--, --, --, --, --, --, --, --, --, --, --, --, nan,
                   0.5418558716773987, 0.24525581300258636,
                   -0.19818709790706635, 0.059832070022821426,

while this was not the case for the previous version
sp = cube07[1000:1040,200,200]
sp.data
masked_array(data=[--, --, --, --, --, --, --, --, --, --, --, --, --,
                   0.5386847853660583, 0.24470342695713043,
                   -0.2502848207950592, 0.10236702114343643,

Note this might be due to the new DRS version, a better way to mask the AO masked filtered range should be implemented

**Comment by saimn** [comment]
This is weird because mpdaf should mask this NaN. I cannot see this if I read the cubes on the server, did you change something to fix it ?

**Comment by saimn** [comment]
Closing in favor of #15.
